export const PAGE_JS_ERROR = 'error'
/**
 * 上报错误类型
 */
export const ERRORTYPES = {
    UNKNOWN: 'UNKNOWN',
    UNKNOWN_FUNCTION: 'UNKNOWN_FUNCTION',
    JAVASCRIPT_ERROR: 'JAVASCRIPT_ERROR',
    LOG_ERROR: 'LOG_ERROR',
    FETCH_ERROR: 'HTTP_ERROR',
    VUE_ERROR: 'VUE_ERROR',
    REACT_ERROR: 'REACT_ERROR',
    RESOURCE_ERROR: 'RESOURCE_ERROR',
    PROMISE_ERROR: 'PROMISE_ERROR',
    ROUTE_ERROR: 'ROUTE_ERROR'
}